name: obs-nb-fdsn-access
channels:
  - conda-forge
dependencies:
  - python=3.11
  - obspy>=1.4
  - matplotlib>=3.8
  - pandas>=2.0
  - cartopy>=0.22
  - jupyter
  - jupyterlab
  - pip
  - pip:
    - nbmake
